export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const ADD_SUB_SECTION = "ADD_SUB_SECTION";
export const EDIT_SECTION = "EDIT_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
